# Generated by Django 4.2.8 on 2023-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_reservationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
